// bifrost-portal/src/components/workflow/WorkflowCanvas.tsx
import React from 'react';
import { GitBranch, Plus, Play, Save } from 'lucide-react';

const WorkflowCanvas = () => {
  return (
    <div className="h-full flex flex-col bg-slate-50">
      <div className="p-4 bg-white border-b flex justify-between items-center">
        <div className="flex items-center space-x-3">
          <h2 className="text-lg font-semibold text-slate-900">Enterprise Sync Pipeline</h2>
          <span className="px-2 py-1 bg-green-100 text-green-700 text-xs font-bold rounded">ACTIVE</span>
        </div>
        <div className="flex items-center space-x-2">
          <button className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium">
            <Play size={16} />
            <span>Execute</span>
          </button>
          <button className="p-2 text-slate-400 hover:bg-slate-100 rounded-lg"><Save size={20}/></button>
        </div>
      </div>
      <div className="flex-1 relative overflow-hidden bg-slate-100 pattern-grid">
        {/* React Flow Canvas would go here */}
        <div className="absolute top-10 left-10 p-6 bg-white border rounded-xl shadow-lg w-64 border-l-4 border-blue-600">
          <div className="flex justify-between items-center mb-4">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Trigger</span>
            <GitBranch size={16} className="text-blue-600" />
          </div>
          <h3 className="font-semibold text-slate-900">Webhook Trigger</h3>
          <p className="text-xs text-slate-500 mt-2">Listening on /api/v1/sfdc-sync</p>
        </div>
        
        <div className="absolute top-10 left-96 p-6 bg-white border rounded-xl shadow-lg w-64 border-l-4 border-orange-500">
          <div className="flex justify-between items-center mb-4">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Connector</span>
            <Share2 size={16} className="text-orange-500" />
          </div>
          <h3 className="font-semibold text-slate-900">Salesforce Search</h3>
          <p className="text-xs text-slate-500 mt-2">Query: SELECT Name FROM Lead</p>
        </div>

        <div className="absolute bottom-10 right-10 flex flex-col space-y-2">
           <button className="w-12 h-12 bg-white border rounded-full shadow-lg flex items-center justify-center text-blue-600 hover:bg-slate-50"><Plus size={24}/></button>
        </div>
      </div>
    </div>
  );
};

export default WorkflowCanvas;

// bifrost-portal/src/components/workflow/WorkflowCanvas.svelte
<script>
  import { GitBranch, Play, Save, Plus, Share2 } from 'lucide-svelte';
</script>

<div class="h-full flex flex-col bg-slate-950">
  <div class="p-6 bg-slate-900 border-b border-slate-800 flex justify-between items-center">
    <div class="flex items-center space-x-3">
      <div class="bg-blue-600/20 p-2 rounded-lg"><GitBranch class="text-blue-500" size={18} /></div>
      <h2 class="text-lg font-bold text-white tracking-tight">Active Workflow Engine</h2>
    </div>
    <div class="flex space-x-3">
       <button class="bg-slate-800 text-slate-300 px-4 py-2 rounded-xl text-sm font-medium hover:bg-slate-700 transition-all flex items-center space-x-2">
         <Save size={16} /><span>Save DAG</span>
       </button>
       <button class="bg-blue-600 text-white px-4 py-2 rounded-xl text-sm font-medium hover:bg-blue-500 shadow-lg shadow-blue-600/20 transition-all flex items-center space-x-2">
         <Play size={16} /><span>Execute</span>
       </button>
    </div>
  </div>

  <div class="flex-1 relative bg-slate-950 overflow-hidden" style="background-image: radial-gradient(circle, #1e293b 1px, transparent 1px); background-size: 30px 30px;">
    <!-- Node Mocks -->
    <div class="absolute top-20 left-20 bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-2xl w-64 border-l-4 border-blue-500">
      <div class="flex justify-between items-center mb-4">
        <span class="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Trigger</span>
        <div class="bg-blue-500/10 p-1.5 rounded"><GitBranch size={14} class="text-blue-500" /></div>
      </div>
      <h3 class="font-bold text-white">Chat Command</h3>
      <p class="text-xs text-slate-400 mt-2">Input: "Analyze Salesforce leads"</p>
    </div>

    <div class="absolute top-20 left-[400px] bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-2xl w-64 border-l-4 border-amber-500">
      <div class="flex justify-between items-center mb-4">
        <span class="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Connector</span>
        <div class="bg-amber-500/10 p-1.5 rounded"><Share2 size={14} class="text-amber-500" /></div>
      </div>
      <h3 class="font-bold text-white">Salesforce Connector</h3>
      <p class="text-xs text-slate-400 mt-2">Action: Search Records</p>
    </div>

    <div class="absolute bottom-10 right-10">
      <button class="bg-blue-600 w-14 h-14 rounded-full flex items-center justify-center text-white shadow-2xl hover:bg-blue-500 transition-all">
        <Plus size={28} />
      </button>
    </div>
  </div>
</div>
