// bifrost-portal/src/components/dashboard/DashboardLayout.svelte
<script>
  import ChartWidget from './ChartWidget.svelte';
  import { LayoutDashboard, Download, Filter } from 'lucide-svelte';

  const stats = [
    { title: 'Total Revenue', value: '$2.4M', trend: '+12%', color: 'border-blue-500' },
    { title: 'Workflow Success', value: '99.2%', trend: '+0.5%', color: 'border-emerald-500' },
    { title: 'Active Nodes', value: '156', trend: 'Stable', color: 'border-amber-500' }
  ];
</script>

<div class="h-full bg-slate-950 overflow-y-auto p-8">
  <div class="flex justify-between items-center mb-10">
    <div class="flex items-center space-x-3">
      <div class="bg-blue-600/20 p-2 rounded-lg"><LayoutDashboard class="text-blue-500" /></div>
      <h2 class="text-2xl font-bold text-white tracking-tight">Enterprise Intelligence</h2>
    </div>
    <div class="flex space-x-3">
      <button class="bg-slate-900 border border-slate-800 px-4 py-2 rounded-xl text-slate-300 hover:bg-slate-800 transition-all text-sm">
        <Filter size={16}/><span>Filters</span>
      </button>
      <button class="bg-blue-600 px-4 py-2 rounded-xl text-white hover:bg-blue-500 shadow-lg shadow-blue-600/20 transition-all text-sm font-medium">
        <Download size={16}/><span>Export Report</span>
      </button>
    </div>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
    {#each stats as stat}
      <div class="bg-slate-900 border border-slate-800 {stat.color} border-l-4 rounded-2xl p-6 shadow-lg">
        <p class="text-slate-400 text-sm font-medium mb-1">{stat.title}</p>
        <div class="flex justify-between items-end">
          <h3 class="text-3xl font-bold text-white">{stat.value}</h3>
          <span class="text-xs font-bold px-2 py-1 rounded bg-slate-800 {stat.trend.startsWith('+') ? 'text-emerald-400' : 'text-slate-400'}">
            {stat.trend}
          </span>
        </div>
      </div>
    {/each}
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <ChartWidget title="Workflow Execution Volume" />
    <ChartWidget title="Agentic Token Consumption" />
  </div>
</div>

// bifrost-portal/src/components/dashboard/DashboardLayout.tsx
import React from 'react';
import { LayoutDashboard, Download, Filter, RefreshCw } from 'lucide-react';

const DashboardLayout = () => {
  return (
    <div className="h-full bg-slate-50 overflow-y-auto">
      <div className="p-6 flex justify-between items-center bg-white border-b sticky top-0 z-10">
        <h2 className="text-2xl font-bold text-slate-900 flex items-center space-x-3">
          <LayoutDashboard className="text-blue-600" />
          <span>Executive Intelligence Overview</span>
        </h2>
        <div className="flex items-center space-x-3">
          <button className="p-2 text-slate-400 hover:bg-slate-100 rounded-lg"><Filter size={20}/></button>
          <button className="p-2 text-slate-400 hover:bg-slate-100 rounded-lg"><RefreshCw size={20}/></button>
          <button className="flex items-center space-x-2 px-4 py-2 bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition-colors font-medium">
            <Download size={16} />
            <span>Export</span>
          </button>
        </div>
      </div>
      
      <div className="p-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {[
          { title: 'Total Revenue (SFDC)', value: '$2.4M', change: '+12%', color: 'blue' },
          { title: 'Active IoT Devices', value: '1,284', change: '-3%', color: 'orange' },
          { title: 'Agentic Flow Success', value: '98.2%', change: '+0.5%', color: 'green' }
        ].map((stat, idx) => (
          <div key={idx} className="bg-white p-6 rounded-2xl shadow-sm border">
            <p className="text-sm font-medium text-slate-500">{stat.title}</p>
            <div className="flex items-end justify-between mt-2">
              <h3 className="text-3xl font-bold text-slate-900">{stat.value}</h3>
              <span className={`text-sm font-bold ${stat.change.startsWith('+') ? 'text-green-600' : 'text-red-600'}`}>{stat.change}</span>
            </div>
          </div>
        ))}
        
        <div className="col-span-1 md:col-span-2 bg-white p-6 rounded-2xl shadow-sm border h-80 flex items-center justify-center">
           <p className="text-slate-400 font-medium">Revenue Trends (ECharts Visualization Placeholder)</p>
        </div>
        
        <div className="col-span-1 bg-white p-6 rounded-2xl shadow-sm border h-80 flex items-center justify-center">
           <p className="text-slate-400 font-medium">Connector Distribution (Pie Chart)</p>
        </div>
      </div>
    </div>
  );
};

export default DashboardLayout;
